server:
  additionalApplications:
    - name: tree
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      project: default

      source:
        repoURL: https://github.com/RasmusGodske/homelab-test.git
        targetRevision: main
        path: tree

      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true