apiVersion: k3d.io/v1alpha3
kind: Simple
name: portainer
servers: 1
agents: 1
kubeAPI:
  hostPort: "6445"
#image: rancher/k3s:v1.20.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 30000-30200:30000-30200
    nodeFilters:
      - server:0

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:* 
