apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tree
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: tree
    repoURL: https://github.com/RasmusGodske/homelab-test.git
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true