apiVersion: v2
name: homelab-reverseproxy-basechart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: traefik
    version: "v10.7.1"
    repository: "https://helm.traefik.io/traefik"
